server:
  port: 8083
eureka:
  instance:
    prefer-ip-address: true
    hostname: bank-discovery
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl: 
      defaultZone: http://bank-dicovery.eubgdbdgarc4bme3.eastus.azurecontainer.io:8761/eureka
    
spring:
  application:
    name: microservice-credit-accounts
  data:
    mongodb:
      #database: BankCreditAccounts
      #host: localhost
      #port: 27017
      #uri: mongodb://localhost:27018/BankCreditAccounts
      uri: mongodb+srv://csanmont:csanmont@cluster0.bxnzqcx.mongodb.net/BankCreditAccounts?retryWrites=true&w=majority
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration      