server:
  port: 8090
eureka:
  instance:
    prefer-ip-address: true
    hostname: bank-discovery
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl: 
      defaultZone: http://bank-dicovery.eubgdbdgarc4bme3.eastus.azurecontainer.io:8761/eureka  


spring:
  application:
    name: microservice-bank-gateway
  cloud:
    gateway:
      routes:
        - id: microservice-passive-accounts
          uri: http://passive-accounts:8082
          predicates: 
          - Path=/**
        - id: microservice-passive-accounts
          uri: http://credit-accounts:8083
          predicates: 
          - Path=/**
        - id: microservice-customers
          uri: bank-customers.afckgbbwaxfyacce.eastus.azurecontainer.io:8081
          predicates: 
          - Path=/**
      discovery:
        locator:
          enabled: true
    loadbalancer:
      ribbon:
        enabled: false
          
 